apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: jarvis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/afod3v/jarvis-dsc-bot:latest
          imagePullPolicy: Always
          command: ["npm", "run", "start:worker"]
          envFrom:
            - configMapRef:
                name: jarvis-config
            - secretRef:
                name: jarvis-secrets
          ports:
            - containerPort: 3002
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "768Mi"
